In [ ]:
import numpy as np

In [ ]:
L = [1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
A = np.array(L)

In [ ]:
for e in L:
    print(e)

In [ ]:
for e in A:
    print(e)

In [ ]:
L.append(4) # you can append to a list

In [ ]:
A.append(4) # AttributeError: 'numpy.ndarray' object has no attribute 'append'
# you can not append to a numpy array

In [ ]:
L + [5] 

In [ ]:
A + np.array([5]) # you can add to a numpy array as in adding a scalar to each element
# a scallar can only be 1 element unless the array is the same length

In [ ]:
A + np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Cant add vectors of different lengths
A + np.array([1, 2])

In [ ]:
2 * A # you can multiply a numpy array by a scalar and it will multiply each element by the scalar

In [ ]:
2 * L # you can multiply a list by a scalar but it will repeat the list that many times

In [16]:
L + L # you can add lists together but it will concatenate them
L2 = []
for e in L:
    L2.append(e + 3)

In [17]:
L2

[4, 5, 6, 7, 8, 9, 10, 11, 12, 7]

In [ ]:
# can also be written as
L2 = [e + 3 for e in L]

In [18]:
#applying a function to each element of an array
A**2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [19]:
#log
np.log(A)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [20]:
#exponential
np.exp(A)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [21]:
#square root
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])